domain: example.com
url: https://example.com

title: frame webdesign
email: wind@example.com
author: Tim Möbus

lang: de

plugins:
  - jekyll-seo-tag

color: "#13ccf9" 

# disqus:
#   shortname: example-com
#
# rrss:
  # discord: hoola
  # facebook: hola
  # twitter: Hola
  # instagram: Hola
  # linkedin: Hola
  # pinterest: hola
  # whatsapp: 123
  # telegram: 123
  # email: email
